### ISSUE TITLE
modify readme 

### ISSUE THREAD

**Issue by ghost** [willamylp/AgendaMongoDB#1]
# Description:
Modify readme with project instructions for software testing

# Tasks:  
- [x] Description on project - @gpersijn
- [x] List techs and frameworks - @Brito-Response 
- [x] List team participants - @gpersijn e @Brito-Response
