### ISSUE TITLE
create docs

### ISSUE THREAD

**Issue by gpersijn** [willamylp/AgendaMongoDB#2]
# Description:
Create docs linking to requirements and user stories by the project

# Tasks:  

## Documento User Story 
- [x] Criar user story do contato - @gpersijn
- [x] Criar user story do usuário - @Brito-Response 
- [x] Descrever testes de aceitação - @gpersijn e @Brito-Response 

## Documento Requisitos
- [x] - Criar no mínimo 20 requisitos do projeto -@gpersijn e @Brito-Response 
- [x] - Criar 4 CRUDS que compõe o Software - @gpersijn e @Brito-Response
