### ISSUE TITLE
document creation and linking

### ISSUE THREAD

**Issue by ghost** [willamylp/AgendaMongoDB#5]
# Description:  
create and link all documents described in the tasks below.
# Tasks:
- [x] file called REQUISITES.md, with the information collected in Task P01 of the projects that describes your project and lists the functional requirements.
- [x] add the Conceptual Model of Entities (UML and MER).  
- [x] add link to readme.
- [x] Create a file called USER_STORIES.md, and organize the User Stories.
- [x] At least 1 User Story per team member must be detailed.
- [x] Put it in the docs/ directory and a link in the README.  @Brito-Response  @gpersijn
